# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPCF9gG38ccG9jpc_wlW1j2KDBLO1V82
"""

!pip install googletrans==3.1.0a0 
import googletrans

from googletrans import Translator

translator = Translator()
out = translator.translate("Bombat",dest="en")

print(out.text)

!pip install pandas

import pandas as pd

df=pd.read_csv("/content/sakkath.csv")

translation=[]
for i in df["comment_body"]:
  out = translator.translate(i,dest="en")
  translation.append(out.text)

translation

df["Translation"]=translation

df.to_csv("sakkath_translated.csv")

